const express=require('express');
const isauthenticated = require("../middleware/authentication.js");
// const { createIndexes } = require('../modals/user');
const router=express.Router();
const {accessChat,fetchChats,createGroupChat,renameGroup,removeFromGroup,addtoGroup} =  require("../components/chats.js");
router.post("/",isauthenticated,accessChat);
router.get("/",isauthenticated,fetchChats);
router.post("/group",isauthenticated,createGroupChat);
router.put("/rename",isauthenticated,renameGroup);
router.put("/groupremove", isauthenticated, removeFromGroup);
router.put("/groupadd", isauthenticated, addtoGroup);
module.exports = router;